name: 'Sops'
description: 'Sops decryption'
inputs:
      env:
        description: "Env name"
        required: true

runs:
  using: "composite"
  steps:
      # Installing Sops binary
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.6.0
        with:
          version: "3.8.1" # Default version is the latest stable version 
        id: install

      # Decrypting the Sops file
      - name: Sops decrypt
        run: |
          sops -d ./infra/terraform/config_env/${{ inputs.env }}/secrets.enc.yaml > ./infra/terraform/config_env/secrets.yaml
        shell: bash

      # Copying the secrets to SSH folder
      - name: Copying the secrets to SSH folder
        run: |
          mkdir -p $HOME/.ssh
          SSH_PRV_KEY=$(yq -r '.SSH_PRV_KEY' ./infra/terraform/config_env/secrets.yaml)
          echo "$SSH_PRV_KEY" > $HOME/.ssh/id_ed25519
          chmod 400 $HOME/.ssh/id_ed25519
        shell: bash
