# name: Apply
# # Runs the workflow on the below events:
# # 1. On push event to develop branch
# # 2. On push event to main branch
# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read
#
# on:
#   push:
#     branches: ["main", "develop"]
#   workflow_dispatch:
#     inputs:
#       env:
#         description: "Target environment"
#         required: true
#         type: choice
#         options:
#           - stage
#           - dev
#           - prod
#
# jobs:
#   # This calls terraform-apply.yaml to do TF apply on dev environment
#   terraform-apply-develop:
#     name: Terraform apply develop
#     if: github.ref == 'refs/heads/develop'
#     uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@develop
#     with:
#       env: dev
#       role-to-assume: "arn:aws:iam::637423277544:role/test_oidc"
#       role-session-name: "aradevrolesession"
#       aws-region-name: "us-east-1"
#
