# name: Check
# # Runs the workflow on the below events:
# # 1. On pull request raised to development branch
# # 2. On pull request raised to main branch
# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read
#
# on:
#   pull_request:
#     branches: ["develop", "main"]
#   push:
#     branches: ["develop", "main"]  
#
# jobs:
#   # This calls terraform-check.yaml to do TF validate and TF plan on dev environment
#   terraform-check-develop:
#     if: github.base_ref == 'develop'
#     name: "TF check for dev env"
#     uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-check.yaml@develop
#     with:
#       env: dev
#       role-to-assume: "arn:aws:iam::637423277544:role/test_oidc"
#       role-session-name: "aradevrolesession"
#       aws-region-name: "us-east-1"
