name: Create Docker Image tag

on:
  workflow_call:
   outputs: 
    docker-image-tag:
      value: ${{ jobs.prerequisite.outputs.short_sha }}_${{ jobs.prerequisite.outputs.date }}
    

jobs:
  prerequisite:
    name: Prerequisite
    runs-on: ubuntu-latest
    # Changing the image tag format to date-gitcommitid
    outputs:
      short_sha: ${{ steps.short-sha.outputs.sha }}
      date: ${{ steps.date.outputs.current_date }}
    steps:
      # Checkout the project
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate short sha
      - name: Get short sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      # Sets current date
      - name: Get current date
        id: date
        run: echo current_date="$(date +'%Y_%m_%d')" >> $GITHUB_OUTPUT
