name: Dr Deploy
# Runs the workflow on the below events:
# 1. On push event to develop branch
# 2. On push event to main branch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "target"
        required: true
      task:
        description: "Action"
        required: false
        type: choice
        options:
          - create
          - destroy

jobs:
  targets:
    outputs:
       targets: ${{ steps.targets.outputs.targets }}
    name: targets
    runs-on: ubuntu-latest
    steps:
      - name: targets
        id: targets
        run: |
           inputed_targets=${{ inputs.targets }}
           reformed_targets=()
           IFS="," read -ra targets <<<$inputed_targets
           for target in ${targets[@]}; do
             reformed_tasks+=("-target"=$target)
           done
           echo "targets=${reformed_tasks[@]}" >> $GITHUB_OUTPUT
        
  terraform-appl-dr:
    needs: [targets]
    if: ${{ inputs.task == 'create' }}
    name: Terraform apply dr
    uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@main
    with:
      env: dev
      role-to-assume: "arn:aws:iam::677276076781:role/odic"
      role-session-name: "acsdrrolesession"
      aws-region-name: "us-east-2"
      # targets: ${{ needs.targets.outputs.targets }}
  
  # This calls terraform-apply.yaml to do TF apply on dr environment
  # terraform-apply-dr:
  #   needs: [targets]
  #   if: ${{ inputs.task == 'create' }}
  #   name: Terraform apply dr
  #   uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@main
  #   with:
  #     env: dev
  #     role-to-assume: "arn:aws:iam::677276076781:role/odic"
  #     role-session-name: "acsdrrolesession"
  #     aws-region-name: "us-east-2"
  #     targets: ${{ needs.targets.outputs.targets }}

  # # This calls terraform-destroy.yaml to do TF destroy on dr environment
  terraform-destroy-dr:
    if: ${{ inputs.task == 'destroy' }}
    needs: [targets]
    name: Terraform destroy dr
    uses: "RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@main"
    with:
      env: dev
      role-to-assume: "arn:aws:iam::677276076781:role/odic"
      role-session-name: "acsdrrolesession"
      aws-region-name: "us-east-2"
      targets: "-destroy ${{ needs.targets.outputs.targets }}"
      task: ${{ inputs.task }}
