name: Dr Deploy
# Runs the workflow on the below events:
# 1. On push event to develop branch
# 2. On push event to main branch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "target"
        required: true
      tasks:
        description: "Action"
        required: true
        type: choice
        options:
          - create
          - destroy

jobs:
  aas:
    outputs:
       tasks: ${{ steps.tasks.outputs.targets }}
    name: targets
    runs-on: ubuntu-latest
    steps:
      - name: targets
        id: targets
        run: |
           tasks=${{ inputs.tasks }}
           reformed_tasks=()
           IFS="," read -ra arr <<<$asd
           for task in ${tasks[@]}; do
             reformed_tasks+=("-target" $task)
           done
           echo "targets=${reformed_tasks[@]}" >> $GITHUB_OUTPUT
        
  
  # This calls terraform-apply.yaml to do TF apply on dr environment
  # terraform-apply-dr:
  #   needs: [aas]
  #   if: ${{ inputs.task == 'create' }}
  #   name: Terraform apply dr
  #   uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@${{needs.as.outputs.branch}} 
  #   with:
  #     env: dev
  #     role-to-assume: "arn:aws:iam::677276076781:role/odic"
  #     role-session-name: "acsdrrolesession"
  #     aws-region-name: "us-east-2"

  # # This calls terraform-destroy.yaml to do TF destroy on dr environment
  terraform-destroy-dr:
    needs: [tasks]
    if: ${{ inputs.task == 'destroy' }}
    name: Terraform destroy dr
    uses: "RTC12-Test/my-sso-infra/.github/workflows/terraform-destroy.yaml@main"
    with:
      env: dev
      role-to-assume: "arn:aws:iam::677276076781:role/odic"
      role-session-name: "acsdrrolesession"
      aws-region-name: "us-east-2"
      targets: ${{ needs.tasks.outputs.targets }}
