name: Dr Deploy
# Runs the workflow on the below events:
# 1. On push event to develop branch
# 2. On push event to main branch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
      task:
        description: "Target environment"
        required: true
        type: choice
        options:
          - create
          - destroy

jobs:
  # This calls terraform-apply.yaml to do TF apply on dr environment
  terraform-apply-dr:
    if: ${{ inputs.task == 'create' }}
    name: Terraform apply dr
    uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@main
    with:
      env: dev
      role-to-assume: "arn:aws:iam::637423277544:role/test_oidc"
      role-session-name: "acsdrrolesession"
      aws-region-name: "us-east-2"

  # This calls terraform-destroy.yaml to do TF destroy on dr environment
  terraform-destroy-dr:
    if: ${{ inputs.task == 'destroy' }}
    name: Terraform apply dr
    uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-apply.yaml@main
    with:
      env: dev
      role-to-assume: "arn:aws:iam::637423277544:role/test_oidc"
      role-session-name: "acsdrrolesession"
      aws-region-name: "us-east-2"
