
name: Get security group

on:
  workflow_call:
    inputs:
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
      get-sg-name:
        description: "AWS region name"
        type: string
        required: true 
    outputs:
      docker-image-url:
        value: ${{ jobs.security_group.outputs.id }}


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  security_group:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.security.outputs.id }}
    steps:
      # Checking out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Logging to aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region-name }}
      - name: Get Security id
        id: security
        run: |   
          id=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=${{ inputs.get-sg-name }}" --query "SecurityGroups[0].GroupId" --output text)
          echo "id=$id" >> $GITHUB_OUTPUT 

