name: Terraform check
# Runs the workflow on the below events:
# 1. On pull request raised to develop branch
# 2. On pull request raised to main branch

on:
  workflow_call:
    # Required inputs
    inputs:
      env:
        description: "Env name"
        type: string
        required: true
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
      aws-kms-key-arn:
        description: "AWS kms key arn to decrypt the secrets"
        type: string
        required: false
        default: arn:aws:kms:us-east-1:637423277544:key/76826c40-ca8d-44a1-9b1e-5a5bd3c75e8a
      docker-image-tag:
        description: "Docker image tag"
        type: string
        required: false
      service-name:
        description: "Service name"
        type: string
        required: false
      sops-enable :
        description: "Enable the sops for sops workflow"
        type: boolean
        required: false
        default: false

jobs:
  # This job runs Terraform Validate
  validate:
    name: Validate (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v4

      # Logging in to aws
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
      
      # Composite runner
      - name: Use sops workflow file
        if: ${{ inputs.sops-enable == true }}
        uses: RTC12-Test/my-sso-infra/.github/actions/sops@develop
        with:
         aws-kms-key-arn : ${{ inputs.aws-kms-key-arn }}
         env: ${{ inputs.env }}
         
      # Install Terraform CLI
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"

      # Intialization of terraform project
      - name: Terraform init
        run: make ENV=${{ inputs.env }} terraform/init

      # Terraform validation is done for terraform modules
      - name: Terraform validate
        run: make ENV=${{ inputs.env }} terraform/validate

  plan:
    # This job runs terraform plan
    name: Plan (${{ inputs. env }})
    needs: [validate]
    uses: RTC12-Test/my-sso-infra/.github/workflows/terraform-plan.yaml@feature/task
    with:
      env: ${{inputs.env}}
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name }}
      aws-region-name: ${{ inputs.aws-region-name }}
      aws-kms-key-arn: ${{ inputs.aws-kms-key-arn }}
      docker-image-tag: ${{ inputs.docker-image-tag }}
      service-name: ${{ inputs.service-name }}
      sops-enable: ${{ inputs.sops-enable }}
