name: Terraform destroy
# Runs the workflow on the below events:
# 1. On push event to develop branch
# 2. On push event to main branch

on:
  workflow_call:
    # Required inputs
    inputs:
      targets:
        description: "targets"
        required: true
        type: string
      env:
        description: "stage | dev | prod"
        required: true
        type: string
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
      
jobs:
  # This job runs Terraform Plan
  plan:
    name: Plan (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v4

      # Logging into AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}

      # Install Terraform CLI
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"

      # Intialiazation of Terraform project
      - name: Terraform init
        run: make ENV=${{ inputs.env }} terraform/init

      # Terraform plan for terraform destroy
      - name: Terraform plan for terraform  destroy
        run: |

          make ENV=${{ inputs.env }} TF_CMD_ARGS='-destroy ${{ inputs.targets }}' terraform/plan

  destroy:
    # This job runs Terraform Destroy
    name: Destroy (${{ inputs.env }})
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    needs: [plan]
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v4

      # Logging into AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}

      # Install Terraform CLI
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"

      # Intialiazation of Terraform project
      - name: Terraform init
        run: make ENV=${{ inputs.env }} terraform/init

      # Destroying Terraform resources
      - name: Terraform destroy resources
        run: make ENV=${{ inputs.env }} TF_CMD_ARGS='-auto-approve -${{ inputs.targets }}' terraform/destroy
