name: Release
# Runs the workflow on the below event:
# 1. On tagging a release
permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  terraform-apply:
    # This will run TF apply on prod environment
    name: "Trigger terraform apply prod"
    uses: AmericanChemicalSociety/acs-sso-infra/.github/workflows/terraform-apply.yaml@v2.0.5
    with:
      env: prod
      role-to-assume: "arn:aws:iam::ixxxx:role/xxxx"
      role-session-name: "acsprodrolesession"
      aws-region-name: "us-east-1"
