name: Upload zip to S3
on:
  workflow_call:
    inputs:
      hello: 
          description: ""
          type: string
      
jobs:
  s3_upload:
    runs-on: ubuntu-latest
    name: S3 Upload
    steps:
      # Logging to aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region-name }}

      - name: Create zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r "${{ inputs.aws-lambda-artifact-filename }}.zip" .

      - name: upload s3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: "cp"
          source: "${{ inputs.aws-lambda-artifact-filename }}.zip"
          destination: "s3://${{inputs.aws-s3-bucket-name}}/${{ inputs.aws-s3-key-name }}"
      
  
  
  
  
