name: Upload zip to S3
on:
  workflow_call:
    inputs:
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
      # aws-lambda-artifact-filename:
      #   description: "Filname of lambda zip"
      #   type: string
      #   required: true
      #   default: ""
      # aws-s3-bucket-name:
      #   description: "Name of s3 bucket"
      #   type: string
      #   required: false
      #   default: ""
      
jobs:
  s3_upload:
    runs-on: ubuntu-latest
    name: S3 Upload
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v4

      # Install aws cli
      - name: Install AWS cli
        id: install-AWS-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      # Logging to aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region-name }}

      - name: Create zip
        run: |
           cd python/
           pip install -r requirements.txt
           zip -r python.zip .

      - name: upload s3
        run: |
          aws s3 cp python.zip s3://acs-sso-dev-jks-cert-bucket 
      
  
  
  
  
